services:
  go:
    build:
      context: ./go
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  atlas:
    image: arigaio/atlas:latest
    working_dir: /app
    volumes:
      - ./go:/app
    depends_on:
      db:
        condition: service_healthy

  seed:
    build:
      context: ./go
    entrypoint: ["/app/seed"]
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
