name: Integration Test

on:
  push:
    branches:
      - main
    paths:
      - "go/**"
  pull_request:
    branches:
      - main
    paths:
      - "go/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add environment variable
        run: |
          echo "DATABASE_URL=postgres://postgres:password@localhost:5432/postgres?search_path=public&sslmode=disable" > .env

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go/go.mod"

      - name: Verify dependencies
        run: go mod verify

      - name: Install dependencies
        run: go mod download

      - name: Install atlas
        run: curl -sSf https://atlasgo.sh | sh

      - name: Run migrations
        run: atlas migrate apply --env prod -u "postgres://postgres:password@localhost:5432/postgres?search_path=public&sslmode=disable" --revisions-schema public

      - name: Seed database
        run: go run cmd/seed/main.go

      - name: Run tests
        run: go test ./internal/handlers -v
